{% set version = '1.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bwstools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bwsTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bwsTools/bwsTools_{{ version }}.tar.gz
  sha256: 1cdff4461a031b28238db5471db5387bca53cb27dfd819eb687e7a906faa37a0

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-crossdes
    - r-dplyr
    - r-igraph
    - r-magrittr
    - r-rlang
    - r-tidyr
  run:
    - r-base
    - r-crossdes
    - r-dplyr
    - r-igraph
    - r-magrittr
    - r-rlang
    - r-tidyr

test:
  commands:
    - $R -e "library('bwsTools')"           # [not win]
    - "\"%R%\" -e \"library('bwsTools')\""  # [win]

about:
  home: https://osf.io/xftvq/
  dev_url: https://github.com/markhwhiteii/bwsTools
  license: MIT
  summary: 'Tools to design best-worst scaling designs (i.e., balanced incomplete block designs)
    and to analyze data from these designs, using aggregate and individual methods such
    as: difference scores, Louviere, Lings, Islam, Gudergan, & Flynn (2013) <doi:10.1016/j.ijresmar.2012.10.002>;
    analytical estimation, Lipovetsky & Conklin (2014) <doi:10.1016/j.jocm.2014.02.001>;
    empirical Bayes, Lipovetsky & Conklin (2015) <doi:10.1142/S1793536915500028>; Elo,
    Hollis (2018) <doi:10.3758/s13428-017-0898-2>; and network-based measures.'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - aspencage
# Package: bwsTools
# Title: Tools for Case 1 Best-Worst Scaling (MaxDiff) Designs
# Version: 1.2.0
# Authors@R: person(given = "Mark", family = "White", email = "markhwhiteii@gmail.com", role = c("aut", "cre"))
# Description: Tools to design best-worst scaling designs (i.e., balanced incomplete block designs) and to analyze data from these designs, using aggregate and individual methods such as: difference scores, Louviere, Lings, Islam, Gudergan, & Flynn (2013) <doi:10.1016/j.ijresmar.2012.10.002>; analytical estimation, Lipovetsky & Conklin (2014) <doi:10.1016/j.jocm.2014.02.001>; empirical Bayes, Lipovetsky & Conklin (2015) <doi:10.1142/S1793536915500028>; Elo, Hollis (2018) <doi:10.3758/s13428-017-0898-2>; and network-based measures.
# License: MIT + file LICENSE
# URL: https://github.com/markhwhiteii/bwsTools
# BugReports: https://github.com/markhwhiteii/bwsTools/issues
# Depends: R (>= 3.5.0)
# Imports: crossdes, dplyr, igraph, magrittr, rlang, tidyr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.0
# VignetteBuilder: knitr
# Suggests: testthat, knitr, rmarkdown, ggplot2
# NeedsCompilation: no
# Packaged: 2020-08-26 15:40:05 UTC; markwhite
# Author: Mark White [aut, cre]
# Maintainer: Mark White <markhwhiteii@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-08-26 22:40:03 UTC
